### ISSUE TITLE
Add facets to GET /definitions as a query parameter

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#110]
API users should be able to GET a (set of) definition that only includes particular facets. that response should include both the summary (collapsed) definition and the full info but still filtered to the set of desired facets. so something like 

```yaml
coordinates: blah blah
described: uh huh
licensed:
  summary:
    facets: 
      - core
      - tests
    attribution: sffdsds
    declared: MIT
  facets:
    core:  core info expanded here
    tests: tests info expanded here
```

If there is only one facet requested then we should consider just having the summary rather than duplicating the data. Then again...

Roughly this logic is already implemented in the `compoentList.js` component in the website. For now we'll likely duplicate so the user can easily and quickly flip bits in the UI the toggle what they are seeing without having to talk to the service.

**Comment by craigez** [comment]
The definitions I see don't seem to match the example in the issue, I assume that's because it's a little out of date?

No facets:
```
coordinates:
  name: react
  namespace: facebook
  provider: github
  revision: edb2b3d3a70bbb6a26670673ac805df34ac23382
  type: git
described:
  sourceLocation:
    provider: github
    revision: edb2b3d3a70bbb6a26670673ac805df34ac23382
    type: git
    url: 'https://github.com/facebook/react'
  tools:
    - clearlydefined/1
```

Has a facet, but no summary:
```
coordinates:
  name: body-parser
  namespace: expressjs
  provider: github
  revision: b2659a7af3b413a2d1df274bef409fe6cdcf6b8f
  type: git
described:
  releaseDate: '2017-09-22'
  sourceLocation:
    provider: github
    revision: b2659a7af3b413a2d1df274bef409fe6cdcf6b8f
    type: git
    url: 'https://github.com/expressjs/body-parser'
  tools:
    - scancode/2.2.1
    - clearlydefined/1
files:
  - attributions:
      - Douglas Christopher Wilson
    path: index.js
  - attributions:
      - Douglas Christopher Wilson
      - Jonathan Ong
    license: MIT
    path: LICENSE
  - license: MIT
    path: package.json
  - license: MIT
    path: README.md
  - attributions:
      - Douglas Christopher Wilson
    path: lib/read.js
  - attributions:
      - Douglas Christopher Wilson
      - Jonathan Ong
    path: lib/types/json.js
  - attributions:
      - Douglas Christopher Wilson
    path: lib/types/raw.js
  - attributions:
      - Douglas Christopher Wilson
    path: lib/types/text.js
  - attributions:
      - Douglas Christopher Wilson
      - Jonathan Ong
    path: lib/types/urlencoded.js
licensed:
  declared: MIT
  facets:
    core:
      attribution:
        parties:
          - Douglas Christopher Wilson
          - Jonathan Ong
        unknown: 2
      discovered:
        expressions:
          - MIT
        unknown: 6
      files: 9
```
