### ISSUE TITLE
Apply curations on a file to all other files with the same hash across versions

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#501]
If someone does a curation on a file we should consider applying that curation to all other files with the same hash across versions.

**Comment by ignacionr** [comment]
A few questions.
1. From the point of view of the API, a tool can inform/edit, or an interactive actor such as the Website, any data point regarding files. That includes data that is not logically tied to its contents (such as the path/name). So let us constraint this request to those properties that are inherently tied to the contents.
1. Shall we go all in with this? I kind of like the idea that within the context of a package, a certain content hash should point to a single set of licensing terms. This would also make it easier/faster to curate.
1. Finally, the whole idea implies that contents do not change license terms over time. Is that a safe assumption?

**Comment by dabutvin** [comment]
In order to share the file level curations across versions of the component we can change the schema of the curations to support this.

Current schema:

```yml
coordinates:
  name: package
  provider: npmjs
  type: npm
revisions:
  1.1.0:
    files:
      - attributions:
          - Copyright (c) 2011-present, You, Inc.
          - Copyright (c) 2011 the original author or authors.
        license: Apache-2.0 OR GPL-2.0-only
        path: java/benchmark/src/main/java/org/rocksdb/benchmark/DbBenchmark.java
      - attributions:
          - Copyright (c) 2011 The Authors.
          - Copyright (c) 2011-present, You, Inc.
        license: BSD-3-Clause
        path: port/win/win_jemalloc.cc
    licensed:
      declared: GPL-2.0-only OR Apache-2.0
```

proposed schema to enable sharing:

```yml
coordinates:
  name: package
  provider: npmjs
  type: npm
revisions:
  1.1.0:
    licensed:
      declared: GPL-2.0-only OR Apache-2.0
files:
    - attributions:
        - Copyright (c) 2011-present, You, Inc.
        - Copyright (c) 2011 the original author or authors.
      license: Apache-2.0 OR GPL-2.0-only
      sha256: 06af3b573a3d485eaeb0cc52a742042e9db1609edcd6ce12827aee43cc36fcf7
    - attributions:
        - Copyright (c) 2011 The Authors.
        - Copyright (c) 2011-present, You, Inc.
      license: BSD-3-Clause
      sha256: 408b64935546f06b88b5a83ef850858b90a4f4177b1df132977fcad256158996
```

so instead of listing the path in the curation for each revision, we list the sha256 and we do not tie the curation on the file level to a particular revision
The declared license and release data curations would still be tied to a specific revision

We would have to extend the definition computes to apply these file-level curations to the individual definitions by hash

**Comment by iamwillbar** [comment]
Thoughts on having it keyed by the hash so it's impossible to have duplicate entries for a hash?

```yaml
coordinates:
  name: package
  provider: npmjs
  type: npm
revisions:
  1.1.0:
    licensed:
      declared: GPL-2.0-only OR Apache-2.0
files:
  06af3b573a3d485eaeb0cc52a742042e9db1609edcd6ce12827aee43cc36fcf7:
    attributions:
        - Copyright (c) 2011-present, You, Inc.
        - Copyright (c) 2011 the original author or authors.
    license: Apache-2.0 OR GPL-2.0-only
  408b64935546f06b88b5a83ef850858b90a4f4177b1df132977fcad256158996:
    attributions:
        - Copyright (c) 2011 The Authors.
        - Copyright (c) 2011-present, You, Inc.
      license: BSD-3-Clause
```
