### ISSUE TITLE
Maven urls are broken

### ISSUE THREAD

**Issue by disulliv** [clearlydefined/service#755]
For example, in [this Maven package](https://dev.clearlydefined.io/definitions/maven/mavencentral/org.assertj/assertj-core/3.16.1), the urls in the current definition point to central.maven.org which is outdated. It should point to [search.maven.org](https://search.maven.org/) like in the sourceLocation.

The current definition urls:
```
  urls:
    download: >-
      http://central.maven.org/maven2/org/assertj/assertj-core/3.16.1/assertj-core-3.16.1.jar
    registry: 'http://central.maven.org/maven2/org/assertj/assertj-core'
    version: 'http://central.maven.org/maven2/org/assertj/assertj-core/3.16.1'
```
