### ISSUE TITLE
Should Curations be validated as SPDX compliant?

### ISSUE THREAD

**Issue by jeffmendoza** [clearlydefined/service#756]
Currently they are not.

Example: https://github.com/clearlydefined/curated-data-dev/pull/1045 Is creating a curation with the license 'asdf'
```yaml
coordinates:
  name: devtools-protocol
  provider: npmjs
  type: npm
revisions:
  0.0.588169:
    licensed:
      declared: asdf
```
However, validation is showing as valid:
![image](https://user-images.githubusercontent.com/771387/88315849-bed0be00-cccb-11ea-9ff8-84041563bcf6.png)

If so, should the should the service reject the curation upon creation, or should the check above block, to allow it to be fixed by the curation reviewer.
