### ISSUE TITLE
enable projects to express *intent*

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#99]
In many (all?) ways we want to adapt to the intent of the projects being harvested. In many cases we can understand their intent (e.g., if there is a LICENSE file it is reasonable to assume that that indicates the expected license). In some cases it get fuzzy:

* LICENSE file at the root but some files have (or don't have) license headers 
* File header licenses that conflict with the root license
* location and type of attribution/copyright holder (e.g., git log is enough for some)
* canonical source location (addressed forking to a certain degree)

Give projects a very simple way to express their intent. For example, a simple YAML file at the root (e.g., `clearly.yaml`) that has a severely trimmed down (and meta) set of content from the definiiton. This should not include the actual data, rather indications of how that data can be found.

```yaml
described:
  facets:
    test:
      - test/**/*
licensed:
  license:
    location: [topLevel, SPDXheader]
  copyright:
    location: gitLog
```
